// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Delete(arg1:string):Promise<void>;

export function Download(arg1:number,arg2:string,arg3:string):Promise<void>;

export function DownloadADB():Promise<string>;

export function KillServer(arg1:string,arg2:number):Promise<void>;

export function List(arg1:string,arg2:string,arg3:string):Promise<main.DirEntries>;

export function MakeDir(arg1:string):Promise<void>;

export function NewADBClient(arg1:string,arg2:number):Promise<Array<string>>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function SelectDevice(arg1:number):Promise<void>;

export function Upload(arg1:string,arg2:string):Promise<void>;
